### ISSUE TITLE
watcher doesn't add any native mods

### ISSUE THREAD

**Issue by OrionFrost** [MolotovCherry/Yet-Another-BG3-Native-Mod-Loader#15]
my game's installed in E:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3 and my game .exes are in the bin folder of that. 
config's here: [config.zip](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/files/13674475/config.zip)
for reference, my native mods are native camera tweaks and baldur's priority cpu optimizer, placed in C:\Users\Komputer\AppData\Local\Larian Studios\Baldur's Gate 3\Plugins of course

**Comment by MolotovCherry** [comment]
Thank you for your report!

Your config looks fine to me. I've pulled the 0.2.0 release right now, but I'll be sending you a new compiled copy with a bunch of logs in it in a moment.

**Comment by OrionFrost** [comment]
watcher launches and stays open in the background as it's supposed to but when it comes to the actual native mods it's as if it didn't exist. no error message, it just hangs in the background and does nothing.

**Comment by MolotovCherry** [comment]
Got it. Let me add some debugs to the source code and recompile it so we can see what's up. Give me a moment~

**Comment by MolotovCherry** [comment]
By the way, while I get this ready, could you go to
`C:\Users\<myusername>\AppData\Local\Larian Studios\Baldur's Gate 3\Plugins\logs`
And find the most recent log file, and see if there's any errors or additional information logged in there?

**Comment by OrionFrost** [comment]
it's currently empty cause prior to this I wiped and reinstalled in hopes of it helping, but I can tell you that the only thing in those logs was a record of the mods being loaded when I launched the game through the 0.1.3 launcher, and completely nothing when launched with the watcher running.

**Comment by MolotovCherry** [comment]
Okay, please see the build [here](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/actions/runs/7211275154), once it's done building (green check mark), it'll auto upload the artifacts and you'll see it on the page like below:

![image](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/assets/13651622/25179a29-8e2d-407c-895a-eabeb9b87483)

Please run the watcher, then fully launch bg3, then after 10 seconds or so after it's launched, you can go to the tray and quit the watcher.

Go again to your log directory, and send me the latest log. Please note it may contain sensitive file paths (such as your username). If you don't want that revealed, you may want to sanitize all paths in the log first (simple search and replace all will do fine)

**Comment by OrionFrost** [comment]
a couple of interesting things:
first: this one loaded all the mods as intended
second: the .log file only contains the information about loading the mods, none of the verbose stuff that I saw in the terminal
third: the watcher from the 2.0 release still didn't do anything 
fourth: after quitting the 2.0 watcher and launching again with the new watcher, nothing loaded (log file once again empty, hence copying from terminal)
[log from terminal1.txt](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/files/13676138/log.from.terminal1.txt)
fifth: after quitting _that_ and launching again with the new watcher, the native mods loaded perfectly
[log from terminal2.txt](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/files/13676159/log.from.terminal2.txt)
the only difference between those last two that I can see is that with the first one I dicked around with other apps while bg3 loaded, while with the second one I touched nothing but the game until I loaded a save and could confirm the camera tweaks work. I will now see if the 2.0 watcher works if I touch absolutely nothing while the game loads

**Comment by OrionFrost** [comment]
update: yes indeed, the watcher from the 2.0 release worked perfectly as long as I didn't do anything like alt+tab to discord while the game loads. my guess is it never worked previously because I _always_ alt+tab away

**Comment by MolotovCherry** [comment]
Thanks for helping debug, as well as the tip of what might be the cause.

For now I think that's all I need. I'll let you know if I need anything else later!

**Comment by MolotovCherry** [comment]
I can't seem to reproduce the bug yet, but I have improved the code regarding this (hopefully it solves it?).

Could you test out the watcher in following for me please? (Ignore the injector tool for now)
https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/actions/runs/7214611595

**Comment by OrionFrost** [comment]
been trying to break it for an hour now, haven't managed

**Comment by OrionFrost** [comment]
game had to freeze for watcher to break. had to close it via the "exe is not responding" dialog, booting the game again after that resulted in no native mods and the terminal not showing anything new.
keept the watcher open the whole time, quitting the game normally and booting it again made it work again.

**Comment by MolotovCherry** [comment]
> game had to freeze for watcher to break. had to close it via the "exe is not responding" dialog, booting the game again after that resulted in no native mods and the terminal not showing anything new. kept the watcher open the whole time, quitting the game normally and booting it again made it work again.

Good to know, I'll alter the code to not wait for the remote threads to exit which should probably stop that. I'll post up a new tester a little later.

**Comment by MolotovCherry** [comment]
Thanks for your report again!

All these bugs are permanently fixed, including the injector.

I will publish the release soon, you are welcome to try it again!
