### ISSUE TITLE
Odd game_root not found--no running game detection

### ISSUE THREAD

**Issue by valharicmageholm** [MolotovCherry/Yet-Another-BG3-Native-Mod-Loader#29]
Possible issue: win10 Prof, tried many variations of format for install_root in config,toml, but utility cannot find/recognize the running game process (BG3)
Sample path:   install_root = 'F:\Games\BG3-junct' 
config.tomal in C:\Users\xps\AppData\Local\Larian Studios\Baldur's Gate 3\Plugins\
I haven't renamed any game-files, and launch from BG3modmanager, let it run for a bit, then try injector.
Launch with launcher selecting DX11 makes no difference.

**Comment by MolotovCherry** [comment]
Thanks for the issue report! I've created a debug build [here](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/actions/runs/7690672708).

You can download it by clicking the "build" link under "Artifacts".

When you run one of the tools, a cmd window will popup and list some paths it's detected. Please double check whether all of those paths are correct at the stated locations. Your junction link should also be followed just fine (it works on my end).

**Comment by MolotovCherry** [comment]
Closed due to [reply](https://www.nexusmods.com/baldursgate3/mods/3052/?tab=posts&jump_to_comment=133215185) on nexus.
> SOLVED, Simply had to run as administrator. Thanks for looking at it.

**Comment by MolotovCherry** [comment]
Okay. I think what's happening is that the injector can't open the game process, so it's skipping it. Perhaps the user the injector was opened under didn't have privileges to open the game process. This is quite rare thing, but yeah, running the tool as admin would fix that.
