### ISSUE TITLE
Failed to get config: Failed to convert json to config

### ISSUE THREAD

**Issue by JoviMedalla31** [MolotovCherry/Yet-Another-BG3-Native-Mod-Loader#3]
Hi Trying to use your mod to inject Dlls 
Only thing I did was change the directory in the config.json file to  "D:\SteamLibrary\steamapps\common\Baldurs Gate 3"

[Crash report and logs.zip](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/files/12909221/Crash.report.and.logs.zip)

**Comment by MolotovCherry** [comment]
This just simply means your config file is malformed. I'll add a clearer message for this soon to make it obvious. Can you post your config file please?

**Comment by MolotovCherry** [comment]
As a peace offering for your troubles, I compiled the latest pre-release for you, including the toml config change above. You will have to re-apply your path to `config.toml`, but it it is easier to use

[launchers.zip](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/files/12909778/launchers.zip)

**Comment by JoviMedalla31** [comment]
Ah I see thanks for this! I'll try it soon!

**Comment by JoviMedalla31** [comment]
Its working! working with camera tweaks and wasd movement, thanks for the help!
