### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by robogena** [MolotovCherry/Yet-Another-BG3-Native-Mod-Loader#38]
Hi Cherry! 👋 Just got a random mod loader crash so I'm sending the report your way. I've never had the watcher crash before so I'm not sure what happened... only thing I've been doing differently is launching the game directly from the exe (so I can avoid hotfix 18 for awhile, lol) and it was otherwise working fine all day.

The watcher crashed immediately on game load and then again when I tried to quit it from the toolbar. Ended the task, restarted the watcher, reloaded the game and now it works perfectly fine, so... ????? ¯\_(ツ)_/¯

YABG3ML Version: Watcher, v0.2.2
Game Version: BG3 DX11, Patch 6, v4.1.1.4763283

If there's other logs or info that you might need, just let me know!

[crashreport.zip](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/files/14351947/crashreport.zip)

**Comment by MolotovCherry** [comment]
Could you create some reproducible steps for me so I can try to get the crash too?

**Comment by robogena** [comment]
Oh god, I'm so powershell illiterate so I don't know if I did this right. I'm trying the debug build and now the watcher exe creates a blank terminal window. Am I supposed to see something there? The exe does work fine though. I was able to generate the log_output at least!

The only thing I could think that I did differently was that I'm in the middle of updating armor stats in a pak, and I think I didn't re-export my mod list prior to launching, like I usually do. I tried to recreate that on both the v0.2.2 and debug watcher builds, but no crash. I have no idea what I did to crash it!

[log_output.txt](https://github.com/MolotovCherry/Yet-Another-BG3-Native-Mod-Loader/files/14352222/log_output.txt)

**Comment by MolotovCherry** [comment]
> Oh god, I'm so powershell illiterate so I don't know if I did this right. I'm trying the debug build and now the watcher exe creates a blank terminal window. Am I supposed to see something there? The exe does work fine though. I was able to generate the log_output at least!

It's alright! I'm very certain the crash is completely fixed now anyways, so you don't need to bother with these steps or with trying to reproduce it. I had enough info from the log to figure it out.

But to answer the questions
> Am I supposed to see something there?
If you did the `> log_output.txt`, then it's normal to see no output, yes!

Thanks again for your crash report! I'll release a new version shortly after I'm done with a few maintenance things.

**Comment by robogena** [comment]
Thank YOU for the speedy fix!! Looking forward to the new version!
